# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
NODES = ENV["ARBY_NODES"].nil? ? 4 : ENV["ARBY_NODES"].to_i

Vagrant.configure(VAGRANTFILE_API_VERSION) do |cluster|

  cluster.vm.box = "hashicorp/precise32"

  # Nodes for Mongo
  (1..NODES).each do |index|
    last_octet = index
    vm_name    = "mongo-#{index}.local"

    cluster.vm.define vm_name do |config|

      config.vm.hostname = vm_name
      config.vm.network :private_network, ip: "192.168.33.3#{last_octet}"
    end
  end

end
